version: '3.3'

services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/web
      - bundle:/bundle
      - node_modules:/web/client/node_modules

volumes:
  database_data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
