version: '3.3'

services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/web
      - bundle:/bundle
      - node_modules:/web/node_modules

volumes:
  database_data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
