version: '3.3'

services:
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/web
      - bundle:/bundle
      - node_modules:/web/node_modules

volumes:
  database_data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
