version: '3.3'

services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/web
      - bundle:/bundle

volumes:
  database_data:
    driver: local
  bundle:
    driver: local
